# Generated by Django 2.2.1 on 2020-01-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('Baisc', 'Basic'), ('Pro', 'Pro'), ('Unlimited', 'Unlimited')], default='Basic', max_length=10)),
                ('price', models.IntegerField()),
                ('stripe_plan_id', models.CharField(max_length=40)),
            ],
        ),
    ]
