# Generated by Django 2.2.1 on 2020-01-15 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200114_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.membership'),
        ),
    ]
