# Generated by Django 2.2.1 on 2020-01-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200117_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.CharField(max_length=3),
        ),
    ]
