# Generated by Django 2.2.1 on 2020-01-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tracks',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
