# Generated by Django 2.2.1 on 2020-04-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default='', max_length=12),
        ),
    ]
