# Generated by Django 2.2.1 on 2020-04-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20200403_1346'),
        ('users', '0009_profile_signup_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='membership',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_plan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='payments.membership'),
        ),
    ]
