# Generated by Django 2.2.1 on 2020-04-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200403_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_plan',
        ),
    ]
