# Generated by Django 2.2.1 on 2020-04-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_current_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
