# Generated by Django 2.2.1 on 2020-01-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tracker',
        ),
    ]
