# Generated by Django 2.2.1 on 2020-04-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_tracker_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='sms',
        ),
    ]
