# Generated by Django 2.2.1 on 2020-04-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_remove_tracker_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='sms',
            field=models.BooleanField(default=False),
        ),
    ]
