# Generated by Django 2.2.1 on 2020-04-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_tracker_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
